### ISSUE TITLE
Licence clarification to use in software distribution

### ISSUE THREAD

**Issue by Hellseher** [cmbant/CAMB#152] opened 2024-01-20 21:20 UTC
Hi,

We would like to clarify the licensing use case in order to include your project in Guix (https://issues.guix.gnu.org/68159). Does the license allow for the project to be used in software distribution without any restrictions?

Refering to this part:

```
LICENSING
-------------------------------

You are licensed to use this software free of charge within the terms of the LGPL (see below), with
these additional conditions:

- Any publication using results of the code must be submitted
  to arXiv.org at the same time as, or before, submitting to a
  journal. arXiv must be updated with a version equivalent to
  that accepted by the journal on journal acceptance.

- If you identify any bugs you report them as soon as confirmed

- This license, the above copyright notices and disclaimer appear
  on ALL copies of the software and documentation, including
  modifications that you make for internal use or for distribution
  ```

**Comment by cmbant** [comment] 2024-01-20 22:28
Probably not. But it's a python program, and on pypi, so it can usually just be listed as a dependence. I didn't understand why you wanted to distribute it separately?

**Comment by troyfigiel** [comment] 2024-01-21 11:58
Hi @cmbant, I was the one who tried to originally package it for GNU Guix, so I might try to clarify. Guix is a package manager with a FOSS only policy, which is how we ended up double-checking the license.

The restrictions as mentioned by @Hellseher are described above the copy of the LGPLv3 in LICENSE.txt. However, the LGPLv3 also states (in section 7)

```
All other non-permissive additional terms are considered "further
restrictions" within the meaning of section 10.  If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term.  If a license document contains
a further restriction but permits relicensing or conveying under this
License, you may add to a covered work material governed by the terms
of that license document, provided that the further restriction does
not survive such relicensing or conveying.
```

I am not a lawyer, but the way I currently read LICENSE.txt, it sounds contradictory, so that either:
- The license is LGPLv3, which means the restrictions Hellseher mentioned, could be removed by the recipients of the software, or
- The license is really a distinct, but then also non-free license.

The license stated on PyPI is LGPLv3, but with the above in mind, I am not sure if this is really what you intended for the software as that would implicitly allow users to remove the additional constraints you stated. We would highly appreciate clarification on your intentions/wishes.

**Comment by cmbant** [comment] 2024-01-21 12:18
I think there is probably now zero overlap with Cosmics, so that inherited licence could likely be removed. Whether there is still overlap with CMBFast is probably debatable. There are other parts of the code with other copyrights, e.g. recfast.f90. The intention was just to get people to report bugs they found and to open source any papers they publish using it, and preserve copyrights.

But I still don't understand why you want a python package as part of a separate package manager? (just seems likely to be more places for updates to get out of sync and break things; I'm wary given someone recently added a conda-forge package of one of my packages, which then, sure enough, broke version compatibility for someone after I updated the main pypi package but the conda package did not update).

**Comment by troyfigiel** [comment] 2024-01-21 14:08
To come back to your question, Guix is a different kind of package manager. It aims for complete reproducibility and building from source. That means, if the package worked / produced specific results at some point in time, a user can always go back to this "point in time" (i.e. commit hash how it is implemented in Guix) and reproduce the exact same results. (A lot of additional information, blogs, etc. can be found on the webpage https://guix.gnu.org/)

We run all the CAMB tests in our build process (and in general tend to run as many tests as possible for other packages as well to spot incompatibility problems), so users can be quite sure the project behaves as expected. That being said, even if our package breaks for whatever reason, that should not come at the cost of the upstream project. Users of an unsupported package manager should file a bug report with their package manager, not here. For example, here is the issue board for Guix: https://issues.guix.gnu.org/

I am aware that unfortunately this does not always stop bug reports from being opened here. If I were in your position and something breaks in Guix, Conda, or any other package manager that you do not officially support, I would close the issue with something like "I am sorry, please try to install the package in the way described in the README. Otherwise, I cannot help you as we do not officially support this package manager. Please file an issue with the appropriate package maintainers instead."

Does this clarify your question?

**Comment by cmbant** [comment] 2024-01-21 14:51
OK thanks!

**Closed** 2024-01-30 15:54 UTC
