### ISSUE TITLE
helper function for reading ini files

### ISSUE THREAD

**Issue by samueldmcdermott** [cmbant/CAMB#141] opened 2023-04-11 18:56 UTC
Trying to figure out where camblib.__camb_MOD_camb_readparamfile as referenced on [line 308](https://github.com/cmbant/CAMB/blob/e8184bb5fd4ec63bd4d69d4568bdec7f0c243aad/camb/camb.py#L308) is defined

Alternately, is there a way to pass a dictionary as a CAMB params instance directly, without using `read_ini`?

**Comment by samueldmcdermott** [comment] 2023-04-11 20:57
Thanks for the response! I looked in the fortran source a little but am not so adept there -- can you link to the fortran line?

Also, when I try `camb.set_params()` with a dictionary as the argument I get `AssertionError: cp should be an instance of CAMBparams` -- is this the expected behavior?

**Comment by cmbant** [comment] 2023-04-11 21:34
Use `camb.set_params(**dict)`

**Comment by samueldmcdermott** [comment] 2023-04-11 22:18
with `camb.set_params(**dict)` I get a `TypeError: expected CustomSources instance, got dict`

**Comment by cmbant** [comment] 2023-04-11 22:25
See the sample code (e.g. https://camb.readthedocs.io/en/latest/CAMBdemo.html box 23)

**Comment by samueldmcdermott** [comment] 2023-04-12 03:19
thanks -- I've seen that way of updating the parameters, but I'm wondering about the default values that get attached to `pars = camb.CAMBparams()`. Basically, how is this function instantiated? Is there a list of parameters and their default values?

**Comment by cmbant** [comment] 2023-04-12 07:31
Have a look at the fortran source of the relevant classes, and the CAMB_SetDefParam() function.
Closing as this is not a bug - please ask questions on CosmoCoffee.

**Closed by cmbant** 2023-04-12 07:31 UTC

**Comment by samueldmcdermott** [comment] 2023-04-12 17:36
I couldn't find CAMB_SetDefParam() by searching GitHub, but my understanding from looking at the source is that values are simply hard-instantiated in the fortran code, which also sets their types -- this seems compatible with what my usage experience, so I agree that my original question is closed (unless I'm misunderstanding something). Thanks for clarifying!
